name: Bug report
description: Create a bug report to help us improve
labels: [ "bug", "needs triage" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Hi there 👋
        Thanks for helping us improve by reporting a bug!
        Please fill in as much information as possible about your bug to avoid unnecessary and time-consuming back-and-forth communication.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I can reproduce the bug with the latest stable release given [here](https://github.com/sidgames5/xenon?tab=readme-ov-file#versions)."
          required: true
        - label: "I made sure that there are **no existing issues** - [open](https://github.com/sidgames5/xenon/issues) or [closed](https://github.com/sidgames5/xenon/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "I made sure that there are **no existing discussions** - [open](https://github.com/sidgames5/xenon/discussions) or [closed](https://github.com/sidgames5/xenon/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "**I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**"
          required: true
        - label: "This issue contains only one bug."
          required: true

  - type: input
    id: app-version
    attributes:
      label: Affected version
      description: "Which version were you using when you found the bug?"
      placeholder: "x.x.x"
    validations:
      required: true

  - type: input
    id: device-type
    attributes:
      label: Affected device tyoe
      description: |
        What device type were you using when you found the bug?
      placeholder: "Example: desktop, laptop, server, virtual machine, etc"
    validations:
      required: true

  - type: dropdown
    id: download
    attributes:
      label: How did you install it?
      options:
        - GitHub releases
        - Official mirror or website
        - Approved mirror or website
        - Third-party mirror or website
        - Built from source

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        What did you do for the bug to show up?

        If you can't cause the bug to show up again reliably (and hence don't have a proper set of steps to give us), please still try to give as many details as possible on how you think you encountered the bug.

      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Tell us what you expect to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Tell us what happens with the steps given above.
    validations:
      required: true

  - type: textarea
    id: screen-media
    attributes:
      label: Screenshots/Screen recordings
      description: |
        A picture or video is worth a thousand words.

        If applicable, drag and drop screenshots or a screen recording to help explain your problem. If your file is too big for Github to accept, try to compress it (ZIP file), or feel free to paste a link to an image/video hoster here instead. Please do not use links from youtube.com. If you need to use a youtube video, please use a link from a privacy-friendly client.

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Please provide any additional information or context that may be relevant, for example:
        * any file or media that led to this bug
        * any crash logs (if you know how to get one)