name: Feature request
description: Suggest an idea for this project
labels: [ "feature", "needs triage" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Hi there 👋
        Thanks for helping us improve by suggesting a feature!
        Please fill in as much information as possible about your feature request to avoid unnecessary and time-consuming back-and-forth communication.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are **no existing issues** - [open](https://github.com/sidgames5/xenon/issues) or [closed](https://github.com/sidgames5/xenon/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "I made sure that there are **no existing discussions** - [open](https://github.com/sidgames5/xenon/discussions) or [closed](https://github.com/sidgames5/xenon/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "**I have taken the time to fill in all the required details. I understand that the report will be dismissed otherwise.**"
          required: true
        - label: "This issue contains only one feature request."
          required: true
        - label: "I checked to see if the feature exists in the latest version."
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the look or behavior to change to suit your needs.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: |
        Describe any problem or limitation you come across while using the distro which would be solved by this feature.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include, for instance sketches, mockups, etc.